# docker run -p 7591:7591 --name boto3-mcp didierdurand/boto3-mcp:ubuntu24.04-latest
# docker run --privileged --name dind-container -d docker:dind

FROM docker:dind
SHELL ["/bin/sh", "-c"]

ARG PYTHON_VERSION="3.12"
ARG MCP_DIR="/app/boto3-mcp/"

# hadolint ignore=DL3018
RUN apk upgrade \
    && apk add --no-cache bash curl wget findutils which grep sed git patch unzip  \
    && apk add --no-cache python3 python3-dev py3-pip

# create the mcp dir
WORKDIR ${MCP_DIR}

# copy requirements
COPY requirements.txt .

# hadolint ignore=SC1091
RUN python${PYTHON_VERSION} -m venv ".venv" \
    && source ".venv/bin/activate" \
    && python${PYTHON_VERSION} -m pip install --upgrade --no-cache-dir -r requirements.txt \
    && rm -rf /root/.cache/pip

# copy app files
COPY README.md .
COPY src/ .

# setup runtime env vars
ENV PYTHON_VERSION=${PYTHON_VERSION}

EXPOSE 7591
