name: 'docker build alpine python'

on:

  workflow_dispatch:  # Allow manual triggering

  push:
    paths:
      - '../../Dockerfile-alpython'
      - '.github/workflows/build_docker_alpython.yaml'
      - '.hadolint.yaml'

jobs:

  build_docker_alpine_python:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DOCKER_FILE: 'Dockerfile-alpython'
      DOCKER_TAGS: 'didierdurand/alpython:latest'

    steps:

      - name: 'checkout git code'
        uses: actions/checkout@v4

      - name: 'prelude'
        run: |
          printenv

      - name: 'log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'lint docker file'
        run: |
          # https://github.com/hadolint/hadolint
          docker run --rm -i -v ${PWD}/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < ${{env.DOCKER_FILE}}

      - name: 'set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'build and push image to Docker Hub'
        # if: github.repository == ${{ env.BASE_REPO }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_TAGS }}