name: 'docker build boto3-mcp'

on:

  workflow_dispatch:  # Allow manual triggering

  push:
    paths:
      - '../../Dockerfile-boto3-mcp'
      - '.github/workflows/build_docker_boto3_mcp.yaml'
      - '.hadolint.yaml'

jobs:

  build_docker_boto3_mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DOCKER_FILE: 'Dockerfile-boto3-mcp'
      DOCKER_TAGS: 'didierdurand/boto3-mcp:latest'

    steps:

      - name: 'checkout git code'
        uses: actions/checkout@v4

      - name: 'prelude'
        run: |
          printenv

#      - name: 'log in to Docker Hub'
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'lint docker file'
        run: |
          # https://github.com/hadolint/hadolint
          docker run --rm -i -v ${PWD}/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < ${{env.DOCKER_FILE}}

      - name: 'set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'build and push image to Docker Hub'
        # if: github.repository == ${{ env.BASE_REPO }}
        uses: docker/build-push-action@v6
        with:
          push: false
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_TAGS }}