name: 'cfn-lint template'

on:
  push:
    paths:
      - '../../cfn-aws-boto3-mcp.yaml'
      - '.github/workflows/lint_cfn.yaml'

jobs:

  lint_CFN_template:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git code'
        uses: actions/checkout@v4
      - name: 'lint CFN template'
        run: |
          pip install cfn-lint
          echo "linting CFN template: cfn-aws-boto3-mcp.yaml"
          cfn-lint --info cfn-aws-boto3-mcp.yaml
